### ISSUE TITLE
Handle escaped single quotes inside xml inside single-quoted string

### ISSUE THREAD

**Issue by jeremyfa** [jeremyfa/language-haxe#1]
![](https://cloud.githubusercontent.com/assets/1103788/14379923/637533be-fdaf-11e5-94a8-1c980d2ff30f.png)

See https://github.com/massiveinteractive/haxe-react/issues/23#issuecomment-207347965

**Comment by jeremyfa** [comment]
@kevinresol Escaped single quotes should now work (escaped double quotes inside double quoted strings as well).

![capture d ecran 2016-04-25 a 12 25 56](https://cloud.githubusercontent.com/assets/164094/14781268/d0c5e55a-0ae1-11e6-8f53-9a20507e0b30.png)

**Comment by kevinresol** [comment]
@jeremyfa yeah tried, thanks!
